# Generated by Django 5.0.6 on 2024-06-09 23:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conference_created_at_conference_qr_code_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
